board: MKS-DLC32 V2.1
name: Retrofit LPKF ProtoMat C60
meta: (26.11.2025) by Gabriel Couto

kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 0
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
axes:
  shared_stepper_disable_pin: I2SO.0

  x:
    steps_per_mm: 126.71
    max_rate_mm_per_min: 1500.0  
    acceleration_mm_per_sec2: 150.0
    max_travel_mm: 325.000
    soft_limits: false 
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: -100.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1500
      settle_ms: 500
    motor0:
      limit_all_pin: gpio.36
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2

  y:
    steps_per_mm: 127.22
    max_rate_mm_per_min: 3000.0
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 205.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: -102.500  
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1500
      settle_ms: 500
    motor0:
      limit_all_pin: gpio.35
      hard_limits: false 
      pulloff_mm: 3.000
      stepstick:
        step_pin: I2SO.5
        direction_pin: I2SO.6:high
        
  z:
    motor0:
      solenoid:
        output_pin: gpio.22:high 
        pwm_hz: 1000
        off_percent: 0
        pull_percent: 100
        hold_percent: 70
        pull_ms: 1000
        direction_invert: true

pwm:
  pwm_hz: 10000
  direction_pin: NO_PIN     
  output_pin: gpio.25
  enable_pin: gpio.26
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 12000
  spindown_ms: 5000
  tool_num: 0
  speed_map: 0=0% 9999=0% 10000=17% 60000=100%
  off_on_alarm: false

i2so:
  bck_pin: gpio.16
  ws_pin: gpio.17
  data_pin: gpio.21

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

sdcard:
  cs_pin: gpio.15
  card_detect_pin: gpio.39




